#!/usr/bin/env node

var request = require('request');

var ip = 'http://127.0.0.1:8000';
//var ip = '192.168.137.4:8000';

console.log('running a git hook');

	//a json object to post
	var payload = {
		'method': 'fill',
		'section': 'all',
		'color': {'r':'FF', 'g': 'FF', 'b': '00'}
	}
	
	request.post(ip, {form: payload}, function (error, response, body) {
		if (!error && response.statusCode == 200) {
			console.log(body); // Print the response.
		}
		else{
			console.log('not good');
			console.log(error);
			console.log(response);
		}
	})